wa72_json_rpc:
    path: "{optionalTrailingSlash}"
    defaults:
        _controller: wa72_jsonrpc.jsonrpccontroller:execute
        optionalTrailingSlash: "/"
    requirements:
        optionalTrailingSlash: "[/]{0,1}"
